/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as coinflip from "./Coinflip";
export type { coinflip };
import type * as fallback from "./Fallback";
export type { fallback };
import type * as fallout from "./Fallout";
export type { fallout };
export * as factories from "./factories";
export type { CoinFlip } from "./Coinflip/Coinflip.sol/CoinFlip";
export { CoinFlip__factory } from "./factories/Coinflip/Coinflip.sol/CoinFlip__factory";
export type { CoinFlipAttack } from "./Coinflip/CoinflipAttack.sol/CoinFlipAttack";
export { CoinFlipAttack__factory } from "./factories/Coinflip/CoinflipAttack.sol/CoinFlipAttack__factory";
export type { Fallback } from "./Fallback/Fallback";
export { Fallback__factory } from "./factories/Fallback/Fallback__factory";
export type { Fallout } from "./Fallout/Fallout";
export { Fallout__factory } from "./factories/Fallout/Fallout__factory";
